### ISSUE TITLE
GNS3 Web-UI - Dark Theme Not Working

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1037]
Community link: https://gns3.com/community/support/gns3-web-ui-dark-theme-not-working

**Comment by keithstowe** [comment]
Dark theme in the web-ui doesn't seem to be working. When I select 'Switch to dark theme' within settings and save it, nothing happens. I have tried several different web browsers and it is the same behaviour on all. I am using GNS3 2.2.18 on Ubuntu 20.04 LTS. Also have the same issue on GNS3 2.2.17.

![Screenshot from 2021-02-16 14-41-07](https://user-images.githubusercontent.com/66480474/108081676-1f10be00-7069-11eb-9987-33625e5a5b7c.png)

**Comment by piotrpekala7** [comment]
@keithstowe 

Could you please open web console in browser and check if sth happens after clicking on switch button?

**Comment by piotrpekala7** [comment]
![s1](https://user-images.githubusercontent.com/31202938/108082971-e4138800-7072-11eb-8146-c006ffea6be5.JPG)
![s2](https://user-images.githubusercontent.com/31202938/108082980-e544b500-7072-11eb-9c06-d7d0b1bbfa99.JPG)
I checked v2.2.19 version and everything works as expected in development mode & in production

**Comment by piotrpekala7** [comment]
also, could you please check gns3server\static\web-ui directory, you should have 2 css files theme-default & theme-default-dark

**Comment by keithstowe** [comment]
> @keithstowe
> 
> Could you please open web console in browser and check if sth happens after clicking on switch button?

When I enable the web console in the browser it displays the following:

The stylesheet http://localhost:3080/static/web-ui/theme-default.css was not loaded because its MIME type, "text/html", is not "text/css". bundled
The stylesheet http://localhost:3080/static/web-ui/theme-default-dark.css was not loaded because its MIME type, "text/html", is not "text/css". bundled
The stylesheet http://localhost:3080/static/web-ui/theme-default-dark.css was not loaded because its MIME type, "text/html", is not "text/css". settings

**Comment by piotrpekala7** [comment]
I found a few threads and analyzed the reasons that might be causing this problem:
https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type
https://stackoverflow.com/questions/53553134/stylesheet-not-loaded-because-of-mime-type-angular-application
https://stackoverflow.com/questions/15737832/angular-js-deep-link-and-browser-refresh
https://stackoverflow.com/questions/48521971/mime-type-error-when-adding-a-css-file-to-angular/49269425
https://stackoverflow.com/questions/51487486/angular-6-refused-to-apply-style-from-because-its-mime-type-text-html
Unfortunately, these tips were applied earlier and the reason is different

**Comment by piotrpekala7** [comment]
I also read the articles here https://www.xspdf.com/resolution/52128823.html & https://www.xspdf.com/resolution/53553134.html => probably there were changes in this area in latest version of angular and we're affected

**Comment by piotrpekala7** [comment]
I will try to implement alternative solution on https://github.com/GNS3/gns3-web-ui/tree/fix_for_theming

**Comment by piotrpekala7** [comment]
Looks like we have it repaired on pr https://github.com/GNS3/gns3-web-ui/pull/1040, needs verification. I had to rewrite this functionality because of changes in last version of angular, connected to ivy compiler

**Comment by piotrpekala7** [comment]
@keithstowe if you want to have it now, you can test our solution for this problem on branch https://github.com/GNS3/gns3-web-ui/tree/fix_for_theming, details how to run web ui you can find in development section in our docs

**Comment by piotrpekala7** [comment]
pr merged
