### ISSUE TITLE
Add "Projects" page link to top menu, or GNS3 logo in top left should link to Projects page

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-web-ui#1041]
Enhancement Request

Version 2.2.18 / 2020.4.0-beta.1

When navigating to "Servers" in the top menu or any entry in the 3-dot, top right menu, there is no way to return to the "Projects" page from any menu.

Please add a link for either the GNS3 logo in the top left, or a "Projects" link in the top menu.

**Comment by piotrpekala7** [comment]
We do not plan to add such a link. At the moment, the user has the option to return to the previously opened project, but not to the project list. Also, if the user already selects a specific project from the list, then he has the option of returning to the project list. We should not add such a link on the servers' page because where would this link lead? The user has the possibility to display the project list of a specific server by clicking on it. Including an extra link can be confusing for some users


We can add a button 'Open recently opened project list', but I don't know if it's an acceptable solution

@grossmj what do you think?

**Comment by piotrpekala7** [comment]
or we can store somewhere list of 5 recently opened projects (the information about server on which project exists should be included)

**Comment by eantowne** [comment]
So, in the current behavior of the webui, When you open the webui from the base URL provided by the VM (http://xxx.xxx.xxx.xxx) it brings you to the projects page. I would consider this to be the "landing page". If you click the servers link, the resulting page does not provide an immediate link back to the projects page. The only way to directly get back to THAT page is by clicking the back button in the browser or by reentering the URL. If there is another way, it is not readily apparent. That is probably my main concern, there is no indication of how to get back to that page.

As a side note, what happened to my other issue I created reference including a link to docs.gns3.com from the help section, it seems to have been deleted?

**Comment by piotrpekala7** [comment]
Understand, you can just click the server name

when it comes to https://github.com/GNS3/gns3-web-ui/issues/1042, it has been fixed and will be available in next release, thanks for reporting!

**Comment by eantowne** [comment]
In regards to #1042, thank you.

Reference this issue, how does the user know that?

**Comment by grossmj** [comment]
I agree that a "Projects" button when in any entry in the 3-dot, top right menu or in the preferences menu could be useful.

It is not necessary when navigating to "Servers" because you can access the "Projects" page by clicking on the server name. Also, this would be confusing with multiple servers. Note that the "Projects" page is the landing page because the web ui is bundled with the server. You can run the web ui in standalone and in this case the landing page is the "Servers" page.

Here is what I propose. 

1. Add a new "List projects" icon next to the delete one for each server on the "Servers" page. This would do the same as clicking on the server name.

![Selection_003](https://user-images.githubusercontent.com/4752614/109130436-a7960980-77a1-11eb-8bc9-b57dceb60392.png)

2. There should not be a "Back to project" in the top bar if there the last project has been closed (using the project settings -> close project)

![Screenshot from 2021-02-25 19-45-14](https://user-images.githubusercontent.com/4752614/109130776-052a5600-77a2-11eb-8877-0e31725eeaea.png)

3. There should be a "Projects" entry if no project is opened so we can go back to the projects page from any of the menus accessible from the projects page.

![Selection_005](https://user-images.githubusercontent.com/4752614/109131551-d2cd2880-77a2-11eb-924d-82628ba1886f.png)

![Selection_006](https://user-images.githubusercontent.com/4752614/109131571-d82a7300-77a2-11eb-9329-affbd70659c7.png)

I hope I haven't missed anything. Please let me know if I did.

**Comment by eantowne** [comment]
I think all of that would resolve things from my perspective.

**Comment by piotrpekala7** [comment]
ref 1 button on servers page added

**Comment by piotrpekala7** [comment]
ref 2 button deactivated when user close project https://github.com/GNS3/gns3-web-ui/commit/d45947999df685bbded22b7adf396d33126c448e

**Comment by piotrpekala7** [comment]
ref 3 added in https://github.com/GNS3/gns3-web-ui/commit/1b0c62c0d1550e656c0021a2e35da6d38331eec5

**Comment by grossmj** [comment]
Looks all good :+1:
