### ISSUE TITLE
Allow IOU or IOS templates to be created

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1307]
It is impossible to manually create IOU or IOS templates. There are 'Not authenticated' messages.

![Screenshot from 2022-04-27 15-55-45](https://user-images.githubusercontent.com/4752614/165481734-7d12dc7d-682e-4dd8-aef2-a295b3f95648.png)

![Screenshot from 2022-04-27 16-03-55](https://user-images.githubusercontent.com/4752614/165483017-fcf12cb3-a6f5-4c58-9bc1-a363a355cf0c.png)

**Comment by rajnikantsolarwinds** [comment]
@grossmj & @piotrpekala7  When I adding IOU template then I getting this error 
![image](https://user-images.githubusercontent.com/101106471/168533419-872cbf71-7692-44d4-aca5-b4552385c81b.png)

**Comment by cristian-ciobanu** [comment]
This does not look like an IOU image name rather than an VM. It has an extension of OVA.
IOU images usually have a .bin extension like this **i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin**
Check the appliance file for an L3 IOU image located on the GNS3 registry page
https://github.com/GNS3/gns3-registry/blob/master/appliances/cisco-iou-l3.gns3a

**Comment by grossmj** [comment]
I am getting the same error

![Screenshot from 2022-05-20 23-06-31](https://user-images.githubusercontent.com/4752614/169568180-1d664934-74e0-469b-8dfd-94cb202a8db2.png)

Make sure you use the same API calls as you used in the image manager, to upload an image: https://apiv3.gns3.net/#/Images/upload_image_v3_images_upload__image_path__post or list existing images: https://apiv3.gns3.net/#/Images/get_images_v3_images_get

The same should be done for IOS router templates (Dynamips)
