### ISSUE TITLE
GNS3 Logo button does not display menu when in controllers page (3.0.0a1)

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-web-ui#1371]
GNS3 3.0.0 alpha 1
GNS3 logo button does not show menu when in the "controllers" page. Mouseover hover does not display "Open Menu". Button shows press action but no menu is displayed. Browser back button should not be the only way to navigate the available pages.

Expected behavior works on "Projects", "Template Preferences", and "Image Manager".

**Comment by grossmj** [comment]
I think we should remove the logo on the "controllers" page because you must first be logged in to access the "Projects", "Template Preferences", and "Image Manager".

**Comment by eantowne** [comment]
What is the thought process behind allowing access to the controllers page if not logged in? 

This kind of determines what menu may or may not be present. Also, not familiar enough with the idea of having multiple controllers to be able to assess any form of security risk from the lack of authentication.

**Comment by eantowne** [comment]
I think that it might be better to have the menu have an entry for the login page, if not logged in. If logged in, then the full menu.

I know this might be a lot of logic to add in, but it provides consistency in navigating the UI.

**Comment by grossmj** [comment]
> I know this might be a lot of logic to add in, but it provides consistency in navigating the UI.

The controllers page can list different controllers, each with different projects, templates and images. So it doesn't make sense that we have a menu with these entries on the controllers page since managing projects, templates and images are specific to a given controller.

I think we should just remove the top banner and logo.

![Screenshot from 2022-09-29 15-56-51](https://user-images.githubusercontent.com/4752614/193051421-df24adcd-a296-43fd-b714-13659d4fa1a3.png)

**Comment by grossmj** [comment]
> I think we should just remove the top banner and logo.

@rajnikantsolarwinds please remove the logo + top banner. Thanks.
