### ISSUE TITLE
Local redirection issue when UI is bundled on Firefox

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#347]

**Comment by ziajka** [comment]
It might be related to caching

**Comment by piotrpekala7** [comment]
@ziajka Could you provide more detailed description?

**Comment by ziajka** [comment]
User is using gns3-gui, clicks on the item in menu "Web UI", browser opens and user sees screen only with background of GNS3 Web UI.

**Comment by piotrpekala7** [comment]
Connected to https://github.com/angular/angular/issues/25589

**Comment by piotrpekala7** [comment]
@ziajka Closed as won't fix. Summary:
-> tested with modifications in app-routing.module - the same result, problem exist only in FF browser
      { path: 'servers', component: ServersComponent },
      { path: 'local', component: ServersComponent },
      { path: 'bundled', component: BundledServerFinderComponent }
-> tested with modifications in BundledServerFinderComponent - expected behaviour when using @angular/router in IE & Chrome
-> changing home component & link url bring the same error in FF

**Comment by piotrpekala7** [comment]
According to angular documentation https://angular.io/guide/router we don't have any code issues
