### ISSUE TITLE
gns3+telnet://0.0.0.0:5000

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-web-ui#943]
Hi

Perhaps that i do a mistake, then sorry....

I have a Server with gns3server and gns3-web-ui. gns3server is started.

I have a other VM with gns3server/gns3-gui/gns3-web-ui installed but i don't use them (perhaps it is important).

- On this VM, i install gns3-webclient-pack
- I use chromium to connect to http://IPServer:3080
- On my lab, i have a running VPCS.
- I use "console".
- Then the log of chromium say :
 
`xdg-open: file 'gns3+telnet://0.0.0.0:5000?name=PC1&project_id=294907d4-df78-4d15-908a-98d06941e844&node_id=e6a7b488-9ee7-49b8-9d2c-e0aec30b9a29' does not exist
`

Do i must to have IPServer instead of 0.0.0.0 ?

**Comment by piotrpekala7** [comment]
are you sure that this question is related to web UI not to webclient pack?

**Comment by piotrpekala7** [comment]
Is the console command well defined in webclientpack? Does this command work normally, ie does it start the console?

**Comment by Raizo62** [comment]
Yes, i believe that "does not exist" is a other bug with webclient pack. I will open an issue.

But, is it good to have the IP 0.0.0.0 instead of IPServer ?

**Comment by grossmj** [comment]
I thought I fixed this problem with version 1.0.0b3? https://github.com/GNS3/gns3-webclient-pack/issues/6

This is definitely a problem with the webclient pack I think.

**Comment by Raizo62** [comment]
> This is definitely a problem with the webclient pack I think.

If I understood correctly, chromium calls "xdg-open 0.0.0.0", and xdg-open uses the "the webclient pack".
Then i think that the problem is not in "the webclient pack".

**Comment by grossmj** [comment]
"0.0.0.0" is kind of expected sometimes, it depends how the server has been started.

https://github.com/GNS3/gns3-webclient-pack/commit/1018c0935fdb56b9b75e310f8453b4e9b4421d07#diff-6df356934591a90825ce31c87d298312R122

**Comment by Raizo62** [comment]
The used command to start gns3server : 

`gns3server -A -L -q --host 0.0.0.0`

**Comment by Raizo62** [comment]
But, if chromium uses 0.0.0.0, how xdg-open and the webclient pack know the "Public IP" of Server ?

**Comment by Raizo62** [comment]
I have tested : chromium seems to use the IP behind host.
But if the Server is behind NAT ?

**Comment by grossmj** [comment]
@Raizo62 

Well, indeed I think you are right. I have ran some tests using the GNS3 VM and I couldn't launch an external console because the server listens on "0.0.0.0".

@piotrpekala7 we need to change the way the console is called.

The server host must be used if `node.console_host` is equal to "0.0.0.0" or "0:0:0:0:0:0:0:0" or "::":

https://github.com/GNS3/gns3-web-ui/blob/aa78dc682ff59dea09c24589ec140f96cfc30066/src/app/components/project-map/log-console/log-console.component.ts#L205L210

Like in this example (you should cover the "0:0:0:0:0:0:0:0" and "::" cases on this line too):

https://github.com/GNS3/gns3-web-ui/blob/b33eb4ce24889ef3482a95daf35c0b2077885528/src/app/components/topology-summary/topology-summary.component.ts#L60

This is done in the desktop Ui as well: https://github.com/GNS3/gns3-gui/commit/410e5353b243e286a24a8761478b65f863a21932

**Comment by piotrpekala7** [comment]
should be fixed in https://github.com/GNS3/gns3-web-ui/commit/1f6f81a02ea7df1ef0b117b156da24386ddd9944

**Comment by piotrpekala7** [comment]
please check after next release

**Comment by piotrpekala7** [comment]
it will be included in web UI 2020.3.2 version
