### ISSUE TITLE
Issue when using the scroll wheel on the web console

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#981]
Using the scroll wheel on the web console also scrolls the scene behind.

Here is a video showing the issue: https://drive.google.com/file/d/16Q68qYKcU3c1R7yG2DS3AQRXNvWpb6QB/view

**Comment by piotrpekala7** [comment]
Unfortunately, in this case, re-styling does not work (you can dynamically switch styles), and also capturing scrolling events does not work properly. I tried to use a special package: https://www.npmjs.com/package/disable-scroll, also unsuccessfully. The problem may be one of the directives we use in the map, but I am not able to determine which and this may be a task which will take a long time. The analysis itself at this level takes several hours. In addition, finding a package that does not allow us to turn off the scroll may not help us, because it would be necessary to find an alternative, and it will not be easy because we use specific functions on the map

**Comment by piotrpekala7** [comment]
I don't want to close it as won't fix, maybe someone will find a solution to this problem in the future

**Comment by piotrpekala7** [comment]
I added workaround https://github.com/GNS3/gns3-web-ui/commit/22c72f411b9ef212f6fde810d05d1c482969abef to avoid this effect when scrolling down, it's better than nothing

**Comment by piotrpekala7** [comment]
verified on Chrome & FF windows
